Fixed an issue with parsing `--json` output when publishing
atlassian/changesets pull request #676
Opened 2021-11-22 10:38 UTC by Andarist

This work has been moved out of https://github.com/atlassian/changesets/pull/674

closes https://github.com/atlassian/changesets/issues/567
closes https://github.com/atlassian/changesets/issues/397

2021-11-22 10:41 UTC, Andarist commented on packages/cli/src/commands/publish/npm-utils.ts
> +      error(stderr);
Added this as suggested [here](https://github.com/atlassian/changesets/pull/674#pullrequestreview-811980332)

For the moment I've refrained from printing `stdout` too because it contains the output of all lifecycle scripts and it feels like this could get really, really, verbose.

A somewhat weird effect is also that with npm7+ this will contain at the end the JSON mentioned by the `error` above this line - but I guess it's not worth trying to remove that.

2021-11-25 22:23 UTC, mitchellhamilton commented on packages/cli/src/utils/getLastJsonObjectFromString.ts
> +};
How would this handle the thing below and similar things with `{` and `}` in strings?

```json
{"blah": "{"}
```

2021-11-25 22:41 UTC, mitchellhamilton requested changes
Could do the suggestion below and log stderr regardless of whether `json?.error` is truthy or not so that users can see stderr just in case we fail to find a json object in the output?

2021-11-25 22:41 UTC, mitchellhamilton commented on packages/cli/src/commands/publish/npm-utils.ts
> +    if (json.error) {
```suggestion
    if (json?.error) {
```

2021-11-25 23:21 UTC, Andarist commented on packages/cli/src/commands/publish/npm-utils.ts
> +    if (json.error) {
Do we have any scenario in which this would be currently needed? Or is it intended to be as an extra precaution?

2021-11-25 23:32 UTC, Andarist commented on packages/cli/src/utils/getLastJsonObjectFromString.ts
> +};
the given example is not even that problematic - we try to parse from `{` till the end, and since this is a valid JSON it just works

if we consider an input like:
```
"{" {"blah": "{"}
```
then it also works because it will fail on the quoted one and retry on the second one (and succeed there)

The idea behind this helper is a little bit indirect but the gist is that even if we catch `{` somewhere, wherever really, be it in a quoted string, be it orphaned, be it part of some other JSON, then we try to parse from it and we simply fail because all of those cases can't be parsed as a single JSON. So we continue and we only parse successfully when we get to the last JSON in the string.

There is also an assumption that we can't have some "invalid" characters after that last JSON - this helper isn't working correctly if we consider such scenario (so `{"a": "b"}randomtext` won't result in a "last json object from string"). Such a scenario has no application for us - because the JSON that we are after should really always be the last thing in the `stdout`/`stderr`

2021-11-25 23:43 UTC, mitchellhamilton commented on packages/cli/src/commands/publish/npm-utils.ts
> +    if (json.error) {
Don't see anything that would require it, just an extra precaution because getting `Uncaught TypeError: Cannot read properties of null (reading 'error')` would be pretty annoying.

2021-11-25 23:48 UTC, mitchellhamilton commented on packages/cli/src/utils/getLastJsonObjectFromString.ts
> +};
> There is also an assumption that we can't have some "invalid" characters after that last JSON - this helper isn't working correctly if we consider such scenario (so {"a": "b"}randomtext won't result in a "last json object from string"). Such a scenario has no application for us - because the JSON that we are after should really always be the last thing in the stdout/stderr

Running `npm publish`(`npm@8.1.0`) in a non-tty env, I get what's shown below. How is it working if there won't be "invalid" characters after the last json given there are "invalid" characters after the json

```
npm ERR! code EOTP
npm ERR! This operation requires a one-time password from your authenticator.
npm ERR! You can provide a one-time password by passing --otp=<code> to the command you ran.
npm ERR! If you already provided a one-time password then it is likely that you either typoed
npm ERR! it, or it timed out. Please try again.
{
  "error": {
    "code": "EOTP",
    "summary": "This operation requires a one-time password from your authenticator.",
    "detail": "You can provide a one-time password by passing --otp=<code> to the command you ran.\nIf you already provided a one-time password then it is likely that you either typoed\nit, or it timed out. Please try again."
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mitchell/.npm/_logs/2021-11-25T22_31_42_856Z-debug.log
```

2021-11-26 09:06 UTC, Andarist commented on packages/cli/src/utils/getLastJsonObjectFromString.ts
> +};
Sorry, I forgot that I've actually put this at the beginning of this function: `str = str.replace(/[^}]*$/, "");`.

So some invalid characters after the last JSON are allowed, but it would break on stuff like:
```
{"some": "json"}

npm ERR!     /some/weird/path/file}name.log
```

This seems acceptable as it's a really bizarre case - we can always refine this logic later when the need arises. Unless you have any idea how to improve this logic in an easy and quick way to handle more scenarios?

2021-11-26 09:09 UTC, Andarist commented on packages/cli/src/commands/publish/npm-utils.ts
> +    if (json.error) {
Ok, I've adjusted the code as suggested and made sure that even if it's missing then we still `return { published: false }` (as this is still within the `if (code !== 0)` block)

2021-11-26 10:12 UTC, mitchellhamilton approved these changes
Given that we'll always log `stderr` now, I'm fine with `getLastJsonObjectFromString` possibly breaking for edge cases since the worse case is someone has to provide a 2fa code with `--otp` rather than the prompt.

2021-11-26 10:26 UTC, merged

2021-11-26 10:29 UTC, peschee commented
👏🏼

2021-12-15 13:59 UTC, Andarist commented
@peschee Sorry, I've missed your comment here - what do you mean? Changesets Action is just using the installed Changesets CLI - and AFAIR it doesn't make direct calls to the npm CLI. So this shouldn't quite affect it directly, unless I'm missing something.